"""add updated_at to trips

Revision ID: a6ea3d2c2802
Revises: df9e00f0406e
Create Date: 2026-03-10 21:37:24.909247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6ea3d2c2802'
down_revision: Union[str, Sequence[str], None] = 'df9e00f0406e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'updated_at')
    # ### end Alembic commands ###
